<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="localhost.localdomain" name="SignInTest" tests="1" failures="0" timestamp="07 Feb 2018 09:22:09 GMT" time="0.000" errors="1">
  <testcase name="signIn" time="0.000" classname="SignInTest">
    <error type="org.testng.TestNGException" message="
Some DataProvider public java.lang.Object[][] SignInTest.credentials(java.lang.String) parameters unresolved:  at 0 type class java.lang.String
">
      <![CDATA[org.testng.TestNGException: Some DataProvider public java.lang.Object[][] SignInTest.credentials(java.lang.String) parameters unresolved:  at 0 type class java.lang.Stringat org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:197)at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:130)at org.testng.internal.Parameters.handleParameters(Parameters.java:706)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- signIn -->
</testsuite> <!-- SignInTest -->
